//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app.Auth
{


    public partial class Login
    {
        protected global::System.Web.UI.WebControls.Panel pnlLoginMessage;

        protected global::System.Web.UI.WebControls.Literal litLoginMessage;

        protected global::System.Web.UI.WebControls.TextBox txtClientEmail;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvClientEmail;

        protected global::System.Web.UI.WebControls.TextBox txtClientPassword;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvClientPassword;

        protected global::System.Web.UI.WebControls.Button btnClientLogin;

        protected global::System.Web.UI.WebControls.TextBox txtAdminUser;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAdminUser;

        protected global::System.Web.UI.WebControls.TextBox txtAdminPassword;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAdminPassword;

        protected global::System.Web.UI.WebControls.TextBox txtAdminCode;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAdminCode;

        protected global::System.Web.UI.WebControls.Button btnAdminLogin;
    }
}
